name: Deploy Vanilla JavaScript PWA HabitTracker App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run linting
        run: npm run lint

      - name: Build Project (if applicable)
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change to the correct build folder

      - name: Upload logs
        run: |
          mkdir -p logs
          echo "Logs uploaded on $(date)" > logs/summary.log
          tar -czf logs.tar.gz logs
        continue-on-error: true
